const maker = require('mumaker')

module.exports = {
    name: "cloud",
    alias: ["cl"],
    desc: "Make text logo.",
    react: "📥",
    category: "Logo Maker",
    start: async(Amarok, m,{pushName,prefix,text, botName}) => {
        if(!text) return m.reply(`Example: *${prefix}cloud Amarok*`);
        maker.textpro("https://textpro.me/create-a-cloud-text-effect-on-the-sky-online-1004.html", [
    `${text}`,]).then((data) => Amarok.sendMessage(m.from, { image: { url: data }, caption: `Generated by ${botName}` }, { quoted: m }))
    .catch((err) => m.reply('An Error occued !'));
    }
}
